[package]
description = "Dependency with fs feature which and does not build with --target=wasm32-unknown-unknown"
license = "MIT"
name = "fs-dep"
version = "0.0.1"
edition = "2018"

[dependencies]
tokio = { version = "1.25.0", features = ["fs"] }
